/*
  AI-Mind Care｜Four-Corner Character Database V2.0

  LEVELS
  -------
  level:"entry"    -> 入門 Entry: 27 characters / 5-question quiz
  level:"basic"    -> Basic additions: 173 characters
                       (Entry 27 + Basic 173 = Basic collection 200)
  level:"advanced" -> Advanced: 500 characters / 20-question quiz

  AUTO-ADVANCED
  -------------
  A new entry without a valid level is treated as Advanced by the webpage.
  You may therefore add a new advanced character in this shorter format:

  { char:"新", code:"0290", pinyin:"xīn", en:"new; fresh" },

  Keep characters.js in the same folder as index.html.
*/

const characters = [
  { char:"一", code:"1000", pinyin:"yī", zh:"一", en:"one", level:"entry" },
  { char:"二", code:"1010", pinyin:"èr", zh:"二", en:"two", level:"entry" },
  { char:"三", code:"1010", pinyin:"sān", zh:"三", en:"three", level:"entry" },
  { char:"王", code:"1010", pinyin:"wáng", zh:"王、君王", en:"king", level:"entry" },
  { char:"天", code:"1043", pinyin:"tiān", zh:"天空、天", en:"sky / heaven", level:"entry" },
  { char:"水", code:"1223", pinyin:"shuǐ", zh:"水", en:"water", level:"entry" },
  { char:"主", code:"0010", pinyin:"zhǔ", zh:"主要、主人", en:"main / master", level:"entry" },
  { char:"立", code:"0010", pinyin:"lì", zh:"站立", en:"stand", level:"entry" },
  { char:"文", code:"0040", pinyin:"wén", zh:"文字、文化", en:"writing / culture", level:"entry" },
  { char:"心", code:"3300", pinyin:"xīn", zh:"心、心靈", en:"heart / mind", level:"entry" },
  { char:"家", code:"3023", pinyin:"jiā", zh:"家、家庭", en:"home / family", level:"entry" },
  { char:"安", code:"3040", pinyin:"ān", zh:"平安、安全", en:"peace / safe", level:"entry" },
  { char:"十", code:"4000", pinyin:"shí", zh:"十", en:"ten", level:"entry" },
  { char:"大", code:"4003", pinyin:"dà", zh:"大", en:"big", level:"entry" },
  { char:"土", code:"4010", pinyin:"tǔ", zh:"土地", en:"earth / soil", level:"entry" },
  { char:"女", code:"4040", pinyin:"nǚ", zh:"女性、女", en:"woman / female", level:"entry" },
  { char:"木", code:"4090", pinyin:"mù", zh:"木、樹木", en:"wood / tree", level:"entry" },
  { char:"中", code:"5000", pinyin:"zhōng", zh:"中間、中國的中", en:"middle / center", level:"entry" },
  { char:"口", code:"6000", pinyin:"kǒu", zh:"口、嘴巴", en:"mouth", level:"entry" },
  { char:"日", code:"6010", pinyin:"rì", zh:"太陽、日子", en:"sun / day", level:"entry" },
  { char:"目", code:"6010", pinyin:"mù", zh:"眼睛、目", en:"eye", level:"entry" },
  { char:"四", code:"6021", pinyin:"sì", zh:"四", en:"four", level:"entry" },
  { char:"人", code:"8000", pinyin:"rén", zh:"人", en:"person", level:"entry" },
  { char:"入", code:"8000", pinyin:"rù", zh:"進入", en:"enter", level:"entry" },
  { char:"八", code:"8000", pinyin:"bā", zh:"八", en:"eight", level:"entry" },
  { char:"小", code:"9000", pinyin:"xiǎo", zh:"小", en:"small", level:"entry" },
  { char:"火", code:"9080", pinyin:"huǒ", zh:"火", en:"fire", level:"entry" },
  { char:"石", code:"1060", pinyin:"shí", zh:"石頭", en:"stone", level:"basic" },
  { char:"太", code:"4003", pinyin:"tài", zh:"太、非常", en:"too / very", level:"basic" },
  { char:"本", code:"4040", pinyin:"běn", zh:"根本、本來", en:"root / origin", level:"basic" },
  { char:"申", code:"5000", pinyin:"shēn", zh:"申明、表達", en:"state / extend", level:"basic" },
  { char:"車", code:"5000", pinyin:"chē", zh:"車輛", en:"vehicle", level:"basic" },
  { char:"夫", code:"5003", pinyin:"fū", zh:"丈夫、男子", en:"man / husband", level:"basic" },
  { char:"央", code:"5003", pinyin:"yāng", zh:"中央", en:"center", level:"basic" },
  { char:"國", code:"6015", pinyin:"guó", zh:"國家", en:"country", level:"basic" },
  { char:"田", code:"6040", pinyin:"tián", zh:"田地", en:"field", level:"basic" },
  { char:"金", code:"8010", pinyin:"jīn", zh:"金、金屬", en:"gold / metal", level:"basic" },
  { char:"全", code:"8010", pinyin:"quán", zh:"全部、完整", en:"whole / complete", level:"basic" },
  { char:"今", code:"8020", pinyin:"jīn", zh:"今天、現在", en:"today / now", level:"basic" },
  { char:"少", code:"9020", pinyin:"shǎo", zh:"少、年少", en:"few / young", level:"basic" },
  { char:"光", code:"9021", pinyin:"guāng", zh:"光、光明", en:"light", level:"basic" },
  { char:"半", code:"9050", pinyin:"bàn", zh:"一半", en:"half", level:"basic" },
  { char:"米", code:"9090", pinyin:"mǐ", zh:"米、稻米", en:"rice", level:"basic" },
  { char:"愛", code:"2024", pinyin:"ài", zh:"愛、喜愛", en:"love / like", level:"basic" },
  { char:"華", code:"4450", pinyin:"huá", zh:"中華、華美", en:"Chinese / splendid", level:"basic" },
  { char:"字", code:"3040", pinyin:"zì", zh:"文字、字", en:"character / word", level:"basic" },
  { char:"生", code:"2510", pinyin:"shēng", zh:"生命、出生", en:"life / birth", level:"basic" },
  { char:"語", code:"0166", pinyin:"yǔ", zh:"語言、話語", en:"language / words", level:"basic" },
  { char:"友", code:"4004", pinyin:"yǒu", zh:"朋友、友善", en:"friend / friendly", level:"basic" },
  { char:"朋", code:"7722", pinyin:"péng", zh:"朋友、同伴", en:"friend / companion", level:"basic" },
  { char:"福", code:"3126", pinyin:"fú", zh:"幸福、福氣", en:"blessing / good fortune", level:"basic" },
  { char:"智", code:"8660", pinyin:"zhì", zh:"智慧、知識", en:"wisdom / intelligence", level:"basic" },
  { char:"慧", code:"5533", pinyin:"huì", zh:"聰慧、智慧", en:"wisdom / intelligence", level:"basic" },
  { char:"的", code:"2762", pinyin:"de", en:"possessive; adjectival suffix", level:"basic" },
  { char:"是", code:"6080", pinyin:"shì", en:"indeed; yes; right; to be; demonstrative pronoun", level:"basic" },
  { char:"不", code:"1090", pinyin:"bù", en:"no; not; un-; negative prefix", level:"basic" },
  { char:"了", code:"1720", pinyin:"le", en:"to finish; particle of completed action", level:"basic" },
  { char:"在", code:"4021", pinyin:"zài", en:"be at; in; on; consist in", level:"basic" },
  { char:"有", code:"4022", pinyin:"yǒu", en:"have; own; possess; exist", level:"basic" },
  { char:"我", code:"2355", pinyin:"wǒ", en:"our; us; i", level:"basic" },
  { char:"他", code:"2421", pinyin:"tā", en:"other; another; he; she", level:"basic" },
  { char:"這", code:"3030", pinyin:"zhè", en:"this; the; here", level:"basic" },
  { char:"個", code:"2620", pinyin:"gè", en:"numerary adjunct; piece; single", level:"basic" },
  { char:"們", code:"2722", pinyin:"men", en:"adjunct pronoun indicate plural", level:"basic" },
  { char:"來", code:"4090", pinyin:"lái", en:"come; coming; return; returning", level:"basic" },
  { char:"上", code:"2110", pinyin:"shàng", en:"top; superior; highest; go up; send up", level:"basic" },
  { char:"和", code:"2690", pinyin:"hé", en:"harmony; peace; peaceful; calm", level:"basic" },
  { char:"地", code:"4411", pinyin:"de / dì", en:"earth; soil; ground; region", level:"basic" },
  { char:"到", code:"1210", pinyin:"dào", en:"go to; arrive; been to", level:"basic" },
  { char:"以", code:"2810", pinyin:"yǐ", en:"by means of; thereby; therefore; consider as; in order to", level:"basic" },
  { char:"說", code:"0861", pinyin:"shuō", en:"speak; say; talk; scold", level:"basic" },
  { char:"時", code:"6404", pinyin:"shí", en:"time; season; era; age", level:"basic" },
  { char:"要", code:"1040", pinyin:"yào", en:"necessary; essential; necessity", level:"basic" },
  { char:"就", code:"0391", pinyin:"jiù", en:"just; simply; to come; go to; to approach", level:"basic" },
  { char:"出", code:"2277", pinyin:"chū", en:"go out; send out; stand; produce", level:"basic" },
  { char:"會", code:"8060", pinyin:"huì", en:"to assemble; meet together; a meeting; an organization", level:"basic" },
  { char:"可", code:"1062", pinyin:"kě", en:"may; can; -able; possibly", level:"basic" },
  { char:"也", code:"4471", pinyin:"yě", en:"also; classical final particle of strong affirmation or identity", level:"basic" },
  { char:"你", code:"2729", pinyin:"nǐ", en:"you; second person pronoun", level:"basic" },
  { char:"對", code:"0440", pinyin:"duì", en:"correct; right; facing; opposed", level:"basic" },
  { char:"能", code:"2121", pinyin:"néng", en:"to be able; can; permitted to; ability", level:"basic" },
  { char:"而", code:"1022", pinyin:"ér", en:"and; and then; and yet; but", level:"basic" },
  { char:"子", code:"1740", pinyin:"zi", en:"offspring; child; fruit; seed of; 1st terrestrial branch", level:"basic" },
  { char:"那", code:"1752", pinyin:"nà", en:"that; that one; those", level:"basic" },
  { char:"得", code:"2624", pinyin:"dé", en:"obtain; get; gain", level:"basic" },
  { char:"於", code:"0823", pinyin:"yú", en:"in; at; on; interjection alas!", level:"basic" },
  { char:"下", code:"1023", pinyin:"xià", en:"under; underneath; below; down; inferior; bring down", level:"basic" },
  { char:"自", code:"2600", pinyin:"zì", en:"self; private; personal; from", level:"basic" },
  { char:"之", code:"3030", pinyin:"zhī", en:"marks preceding phrase as modifier of following phrase; it; him her; them; go to", level:"basic" },
  { char:"年", code:"8050", pinyin:"nián", en:"year; new-years; person's age", level:"basic" },
  { char:"過", code:"3730", pinyin:"guò", en:"pass; pass through; go across", level:"basic" },
  { char:"發", code:"1224", pinyin:"fā", en:"issue; dispatch; send out", level:"basic" },
  { char:"後", code:"2224", pinyin:"hòu", en:"behind; rear; after; descendents", level:"basic" },
  { char:"作", code:"2821", pinyin:"zuò", en:"make; work; compose; write; act; perform", level:"basic" },
  { char:"用", code:"7722", pinyin:"yòng", en:"use; employ; apply", level:"basic" },
  { char:"道", code:"3830", pinyin:"dào", en:"path; road; street; method", level:"basic" },
  { char:"行", code:"2122", pinyin:"xíng", en:"go; walk; move; travel; circulate", level:"basic" },
  { char:"所", code:"7222", pinyin:"suǒ", en:"place; location; numerary adjunct", level:"basic" },
  { char:"然", code:"2333", pinyin:"rán", en:"yes; certainly; pledge; promise", level:"basic" },
  { char:"種", code:"2291", pinyin:"zhǒng", en:"seed; race; offspring; to plant", level:"basic" },
  { char:"事", code:"5000", pinyin:"shì", en:"affair; matter; business; to serve; accident", level:"basic" },
  { char:"成", code:"5320", pinyin:"chéng", en:"completed; finished; fixed", level:"basic" },
  { char:"方", code:"0022", pinyin:"fāng", en:"a square; rectangle; a region; local", level:"basic" },
  { char:"多", code:"2720", pinyin:"duō", en:"much; many; more than; over", level:"basic" },
  { char:"經", code:"2191", pinyin:"jīng", en:"classic works; pass through", level:"basic" },
  { char:"麼", code:"0023", pinyin:"me", en:"interrogative final particle; insignificant; small; tiny", level:"basic" },
  { char:"去", code:"4073", pinyin:"qù", en:"go away; leave; depart", level:"basic" },
  { char:"法", code:"3413", pinyin:"fǎ", en:"law; rule; regulation", level:"basic" },
  { char:"學", code:"7740", pinyin:"xué", en:"learning; knowledge; school", level:"basic" },
  { char:"如", code:"4640", pinyin:"rú", en:"if; supposing; as if; like; as", level:"basic" },
  { char:"都", code:"4762", pinyin:"dōu / dū", en:"metropolis; capital; all; the whole; elegant", level:"basic" },
  { char:"同", code:"7722", pinyin:"tóng", en:"same; similar; together with", level:"basic" },
  { char:"現", code:"1611", pinyin:"xiàn", en:"appear; manifest; become visible", level:"basic" },
  { char:"當", code:"9060", pinyin:"dāng", en:"bear; accept; undertake; just", level:"basic" },
  { char:"沒", code:"3714", pinyin:"méi", en:"not; have not; none; to drown", level:"basic" },
  { char:"動", code:"2412", pinyin:"dòng", en:"move; happen; movement; action", level:"basic" },
  { char:"面", code:"1060", pinyin:"miàn", en:"face; surface; plane; side; dimension", level:"basic" },
  { char:"起", code:"4780", pinyin:"qǐ", en:"rise; stand up; go up; begin", level:"basic" },
  { char:"看", code:"2060", pinyin:"kàn", en:"look; see; examine; scrutinize", level:"basic" },
  { char:"定", code:"3080", pinyin:"dìng", en:"decide; settle; fix", level:"basic" },
  { char:"分", code:"8022", pinyin:"fēn", en:"divide; small unit of time etc.", level:"basic" },
  { char:"還", code:"3630", pinyin:"hái", en:"still; yet; also", level:"basic" },
  { char:"進", code:"3030", pinyin:"jìn", en:"advance; make progress; enter", level:"basic" },
  { char:"好", code:"4744", pinyin:"hǎo", en:"good; excellent; fine; well", level:"basic" },
  { char:"部", code:"0762", pinyin:"bù", en:"part; division; section", level:"basic" },
  { char:"其", code:"4480", pinyin:"qí", en:"his; her; its", level:"basic" },
  { char:"些", code:"2110", pinyin:"xiē", en:"little; few; rather; somewhat", level:"basic" },
  { char:"樣", code:"4893", pinyin:"yàng", en:"shape; form; pattern", level:"basic" },
  { char:"理", code:"1611", pinyin:"lǐ", en:"reason; logic; manage", level:"basic" },
  { char:"她", code:"4441", pinyin:"tā", en:"she; her", level:"basic" },
  { char:"前", code:"8022", pinyin:"qián", en:"in front; forward; preceding", level:"basic" },
  { char:"開", code:"7744", pinyin:"kāi", en:"open; initiate; begin; start", level:"basic" },
  { char:"但", code:"2621", pinyin:"dàn", en:"only; but; however; yet", level:"basic" },
  { char:"因", code:"6043", pinyin:"yīn", en:"cause; reason; by; because (of)", level:"basic" },
  { char:"只", code:"6080", pinyin:"zhǐ", en:"only; just; simply", level:"basic" },
  { char:"從", code:"2828", pinyin:"cóng", en:"from; by; since", level:"basic" },
  { char:"想", code:"4633", pinyin:"xiǎng", en:"think; speculate; plan", level:"basic" },
  { char:"實", code:"3080", pinyin:"shí", en:"real; true; solid", level:"basic" },
  { char:"軍", code:"3750", pinyin:"jūn", en:"army; military; soldiers; troops", level:"basic" },
  { char:"者", code:"4460", pinyin:"zhě", en:"that which; he who; those who", level:"basic" },
  { char:"意", code:"0033", pinyin:"yì", en:"thought; idea; opinion; think", level:"basic" },
  { char:"無", code:"8033", pinyin:"wú", en:"negative; no; not; lack", level:"basic" },
  { char:"力", code:"4002", pinyin:"lì", en:"power; capability; influence", level:"basic" },
  { char:"它", code:"3071", pinyin:"tā", en:"it; other", level:"basic" },
  { char:"與", code:"7780", pinyin:"yǔ", en:"and; with; to; for; give; grant", level:"basic" },
  { char:"長", code:"7173", pinyin:"zhǎng", en:"long; length; excel in; leader", level:"basic" },
  { char:"把", code:"5701", pinyin:"bǎ", en:"hold; take; guard; regard as", level:"basic" },
  { char:"機", code:"4295", pinyin:"jī", en:"machine; moment; chance", level:"basic" },
  { char:"民", code:"7774", pinyin:"mín", en:"people; subjects; citizens", level:"basic" },
  { char:"第", code:"8822", pinyin:"dì", en:"sequence; number; grade; degree", level:"basic" },
  { char:"公", code:"8073", pinyin:"gōng", en:"fair; equitable; public; duke", level:"basic" },
  { char:"此", code:"2111", pinyin:"cǐ", en:"this; these; in this case; then", level:"basic" },
  { char:"已", code:"1771", pinyin:"yǐ", en:"already; finished; stop", level:"basic" },
  { char:"工", code:"1010", pinyin:"gōng", en:"labor; work; worker; laborer", level:"basic" },
  { char:"使", code:"2520", pinyin:"shǐ", en:"cause; send on a mission; order; envoy", level:"basic" },
  { char:"情", code:"9502", pinyin:"qíng", en:"feeling; sentiment; emotion", level:"basic" },
  { char:"明", code:"6702", pinyin:"míng", en:"bright; light; brilliant; clear", level:"basic" },
  { char:"性", code:"9501", pinyin:"xìng", en:"nature; character; sex", level:"basic" },
  { char:"知", code:"8640", pinyin:"zhī", en:"know; perceive; comprehend", level:"basic" },
  { char:"又", code:"1740", pinyin:"yòu", en:"and; also; again", level:"basic" },
  { char:"關", code:"7777", pinyin:"guān", en:"frontier pass; close; relation", level:"basic" },
  { char:"點", code:"6136", pinyin:"diǎn", en:"dot; speck; spot; point", level:"basic" },
  { char:"正", code:"1010", pinyin:"zhèng", en:"right; proper; correct", level:"basic" },
  { char:"業", code:"3290", pinyin:"yè", en:"profession; business; trade", level:"basic" },
  { char:"外", code:"2320", pinyin:"wài", en:"out; outside; external; foreign", level:"basic" },
  { char:"將", code:"2724", pinyin:"jiāng", en:"will; going to; future; general", level:"basic" },
  { char:"兩", code:"1022", pinyin:"liǎng", en:"two; both; pair", level:"basic" },
  { char:"高", code:"0022", pinyin:"gāo", en:"high; tall; lofty; elevated", level:"basic" },
  { char:"間", code:"7760", pinyin:"jiān", en:"interval; space; place; between", level:"basic" },
  { char:"由", code:"5060", pinyin:"yóu", en:"cause; reason; from", level:"basic" },
  { char:"問", code:"7760", pinyin:"wèn", en:"ask (about); inquire after", level:"basic" },
  { char:"很", code:"2723", pinyin:"hěn", en:"very; quite; much", level:"basic" },
  { char:"最", code:"6014", pinyin:"zuì", en:"most; extremely; exceedingly", level:"basic" },
  { char:"重", code:"2010", pinyin:"zhòng", en:"heavy; weighty; double", level:"basic" },
  { char:"並", code:"8010", pinyin:"bìng", en:"equal to; side by side; also; what is more; both", level:"basic" },
  { char:"物", code:"2752", pinyin:"wù", en:"thing; substance; creature", level:"basic" },
  { char:"手", code:"2050", pinyin:"shǒu", en:"hand", level:"basic" },
  { char:"應", code:"0023", pinyin:"yīng", en:"should; ought to; must", level:"basic" },
  { char:"戰", code:"6355", pinyin:"zhàn", en:"war; fighting; battle", level:"basic" },
  { char:"向", code:"2722", pinyin:"xiàng", en:"toward; direction; trend", level:"basic" },
  { char:"頭", code:"1118", pinyin:"tóu", en:"head; top; chief; first; boss", level:"basic" },
  { char:"體", code:"7521", pinyin:"tǐ", en:"body; group; class; body", level:"basic" },
  { char:"政", code:"1814", pinyin:"zhèng", en:"government; political affairs", level:"basic" },
  { char:"美", code:"8043", pinyin:"měi", en:"beautiful; pretty; pleasing", level:"basic" },
  { char:"相", code:"4690", pinyin:"xiāng", en:"mutual; reciprocal; each other", level:"basic" },
  { char:"見", code:"6021", pinyin:"jiàn", en:"observe; behold; perceive", level:"basic" },
  { char:"被", code:"3424", pinyin:"bèi", en:"passive indicator 'by'; bedding", level:"basic" },
  { char:"利", code:"2290", pinyin:"lì", en:"gains; advantage; profit", level:"basic" },
  { char:"什", code:"2420", pinyin:"shén", en:"file of ten soldiers; mixed; miscellaneous", level:"basic" },
  { char:"等", code:"8834", pinyin:"děng", en:"rank; grade; wait; equal; 'etc.'", level:"basic" },
  { char:"產", code:"0021", pinyin:"chǎn", en:"give birth; bring forth; produce", level:"basic" },
  { char:"或", code:"5310", pinyin:"huò", en:"or; either; else; perhaps", level:"basic" },
  { char:"新", code:"0292", pinyin:"xīn", en:"new; recent; fresh", level:"basic" },
  { char:"己", code:"1771", pinyin:"jǐ", en:"self; oneself; personal; private; 6th heavenly stem", level:"basic" },
  { char:"制", code:"2220", pinyin:"zhì", en:"system; establish; overpower", level:"basic" },
  { char:"身", code:"2740", pinyin:"shēn", en:"body; trunk; hull; rad. no. 158", level:"basic" },
  { char:"果", code:"6090", pinyin:"guǒ", en:"fruit; result", level:"basic" },
  { char:"加", code:"4600", pinyin:"jiā", en:"add to; increase; augment", level:"basic" },
  { char:"西", code:"1060", pinyin:"xī", en:"west(ern); westward; occident", level:"basic" },
  { char:"斯", code:"4282", pinyin:"sī", en:"this; thus; such; to lop off; emphatic particle", level:"basic" },
  { char:"月", code:"7722", pinyin:"yuè", en:"moon; month; KangXi radical 74", level:"advanced" },
  { char:"話", code:"0266", pinyin:"huà", en:"speech; talk; language; dialect", level:"advanced" },
  { char:"合", code:"8060", pinyin:"hé", en:"combine; unite; join; gather", level:"advanced" },
  { char:"回", code:"6060", pinyin:"huí", en:"return; turn around; a time", level:"advanced" },
  { char:"特", code:"2454", pinyin:"tè", en:"special; unique; distinguished", level:"advanced" },
  { char:"代", code:"2324", pinyin:"dài", en:"replace; replacement (of person or generation); era; generation", level:"advanced" },
  { char:"內", code:"4022", pinyin:"nèi", en:"inside; interior; domestic", level:"advanced" },
  { char:"信", code:"2026", pinyin:"xìn", en:"trust; believe; letter", level:"advanced" },
  { char:"表", code:"5073", pinyin:"biǎo", en:"show; express; manifest", level:"advanced" },
  { char:"化", code:"2421", pinyin:"huà", en:"change; convert; reform; -ize", level:"advanced" },
  { char:"老", code:"4471", pinyin:"lǎo", en:"old; aged; experienced", level:"advanced" },
  { char:"給", code:"2896", pinyin:"gěi", en:"give; by; for", level:"advanced" },
  { char:"世", code:"4471", pinyin:"shì", en:"generation; world; era", level:"advanced" },
  { char:"位", code:"2021", pinyin:"wèi", en:"throne; position; post; rank; status; seat", level:"advanced" },
  { char:"次", code:"3718", pinyin:"cì", en:"order; sequence; next", level:"advanced" },
  { char:"度", code:"0024", pinyin:"dù", en:"degree; system; manner; to consider", level:"advanced" },
  { char:"門", code:"7777", pinyin:"mén", en:"gate; door; entrance", level:"advanced" },
  { char:"任", code:"2221", pinyin:"rèn", en:"trust to; rely on; appoint; to bear", level:"advanced" },
  { char:"常", code:"9022", pinyin:"cháng", en:"common; normal; frequent", level:"advanced" },
  { char:"先", code:"2421", pinyin:"xiān", en:"first; former; previous", level:"advanced" },
  { char:"海", code:"3815", pinyin:"hǎi", en:"sea; ocean; maritime", level:"advanced" },
  { char:"通", code:"3730", pinyin:"tōng", en:"pass through; common; communicate", level:"advanced" },
  { char:"教", code:"4844", pinyin:"jiào", en:"teach; class", level:"advanced" },
  { char:"兒", code:"7721", pinyin:"ér", en:"son; child; oneself; final part", level:"advanced" },
  { char:"原", code:"7129", pinyin:"yuán", en:"source; origin; beginning", level:"advanced" },
  { char:"東", code:"5090", pinyin:"dōng", en:"east; eastern; eastward", level:"advanced" },
  { char:"聲", code:"4740", pinyin:"shēng", en:"sound; voice; noise; tone; music", level:"advanced" },
  { char:"提", code:"5608", pinyin:"tí", en:"hold in hand; lift in hand", level:"advanced" },
  { char:"及", code:"1724", pinyin:"jí", en:"extend; reach; come up to; and", level:"advanced" },
  { char:"比", code:"2171", pinyin:"bǐ", en:"to compare; liken; comparison; than", level:"advanced" },
  { char:"員", code:"6080", pinyin:"yuán", en:"member; personnel; staff member", level:"advanced" },
  { char:"解", code:"2725", pinyin:"jiě", en:"loosen; unfasten; untie; explain", level:"advanced" },
  { char:"名", code:"2760", pinyin:"míng", en:"name; rank; title", level:"advanced" },
  { char:"真", code:"2180", pinyin:"zhēn", en:"real; actual; true", level:"advanced" },
  { char:"論", code:"0862", pinyin:"lùn", en:"debate; discuss; discourse", level:"advanced" },
  { char:"處", code:"2124", pinyin:"chù", en:"place; locale; department", level:"advanced" },
  { char:"走", code:"4080", pinyin:"zǒu", en:"walk; go on foot; run; leave", level:"advanced" },
  { char:"義", code:"8055", pinyin:"yì", en:"right conduct; righteousness", level:"advanced" },
  { char:"各", code:"2760", pinyin:"gè", en:"each; individually; every", level:"advanced" },
  { char:"幾", code:"2225", pinyin:"jǐ", en:"how many? how much?; a few; some", level:"advanced" },
  { char:"認", code:"0763", pinyin:"rèn", en:"recognize; know; understand", level:"advanced" },
  { char:"條", code:"2829", pinyin:"tiáo", en:"clause; condition; string; stripe", level:"advanced" },
  { char:"平", code:"1040", pinyin:"píng", en:"flat; level; even; peaceful", level:"advanced" },
  { char:"系", code:"2090", pinyin:"xì", en:"system; line; link; connection", level:"advanced" },
  { char:"氣", code:"8091", pinyin:"qì", en:"air; gas; steam", level:"advanced" },
  { char:"題", code:"6180", pinyin:"tí", en:"forehead; title; headline; theme", level:"advanced" },
  { char:"活", code:"3216", pinyin:"huó", en:"live; exist; survive; lively", level:"advanced" },
  { char:"爾", code:"1022", pinyin:"ěr", en:"you; that; those; final particle", level:"advanced" },
  { char:"更", code:"1050", pinyin:"gèng", en:"more; still further; much more", level:"advanced" },
  { char:"別", code:"6220", pinyin:"bié", en:"separate; other; do not", level:"advanced" },
  { char:"打", code:"5102", pinyin:"dǎ", en:"strike; hit; beat; fight; attack", level:"advanced" },
  { char:"變", code:"2240", pinyin:"biàn", en:"change; transform; alter; rebel", level:"advanced" },
  { char:"神", code:"3520", pinyin:"shén", en:"spirit; god; supernatural being", level:"advanced" },
  { char:"總", code:"2693", pinyin:"zǒng", en:"collect; overall; altogether", level:"advanced" },
  { char:"何", code:"2122", pinyin:"hé", en:"what; why; where", level:"advanced" },
  { char:"電", code:"1071", pinyin:"diàn", en:"electricity; electric; lightning", level:"advanced" },
  { char:"數", code:"5844", pinyin:"shù", en:"number; several; count; fate", level:"advanced" },
  { char:"報", code:"4744", pinyin:"bào", en:"report; tell; announce", level:"advanced" },
  { char:"才", code:"4020", pinyin:"cái", en:"talent; ability; just; only", level:"advanced" },
  { char:"結", code:"2496", pinyin:"jié", en:"knot; tie; join; connect", level:"advanced" },
  { char:"反", code:"7124", pinyin:"fǎn", en:"reverse; opposite; contrary", level:"advanced" },
  { char:"受", code:"2040", pinyin:"shòu", en:"receive; accept; get; bear", level:"advanced" },
  { char:"量", code:"6010", pinyin:"liàng", en:"measure; quantity; capacity", level:"advanced" },
  { char:"再", code:"1044", pinyin:"zài", en:"again; twice; re-", level:"advanced" },
  { char:"感", code:"5333", pinyin:"gǎn", en:"feel; perceive; emotion", level:"advanced" },
  { char:"建", code:"1540", pinyin:"jiàn", en:"build; establish; erect", level:"advanced" },
  { char:"務", code:"1822", pinyin:"wù", en:"affairs; business; must; should", level:"advanced" },
  { char:"做", code:"2824", pinyin:"zuò", en:"work; make; act", level:"advanced" },
  { char:"接", code:"5004", pinyin:"jiē", en:"receive; continue; catch; connect", level:"advanced" },
  { char:"必", code:"3300", pinyin:"bì", en:"surely; most certainly; must", level:"advanced" },
  { char:"場", code:"4612", pinyin:"chǎng", en:"open space; field; market", level:"advanced" },
  { char:"件", code:"2520", pinyin:"jiàn", en:"numerary adjunct for article; matter", level:"advanced" },
  { char:"計", code:"0460", pinyin:"jì", en:"plan; plot; stratagem; scheme", level:"advanced" },
  { char:"管", code:"8877", pinyin:"guǎn", en:"pipe; tube; duct; woodwind music", level:"advanced" },
  { char:"期", code:"4782", pinyin:"qī", en:"period of time; date; time limit", level:"advanced" },
  { char:"市", code:"0022", pinyin:"shì", en:"market; fair; city; town; trade", level:"advanced" },
  { char:"直", code:"4071", pinyin:"zhí", en:"straight; erect; vertical", level:"advanced" },
  { char:"德", code:"2423", pinyin:"dé", en:"ethics; morality; virtue", level:"advanced" },
  { char:"資", code:"3780", pinyin:"zī", en:"property; wealth; capital", level:"advanced" },
  { char:"命", code:"8062", pinyin:"mìng", en:"life; destiny; fate; luck; an order", level:"advanced" },
  { char:"山", code:"2277", pinyin:"shān", en:"mountain; hill; peak", level:"advanced" },
  { char:"指", code:"5106", pinyin:"zhǐ", en:"finger; toe; point; indicate", level:"advanced" },
  { char:"克", code:"4021", pinyin:"kè", en:"gram; overcome; transliteration", level:"advanced" },
  { char:"許", code:"0864", pinyin:"xǔ", en:"allow; permit; promise; betroth", level:"advanced" },
  { char:"統", code:"2091", pinyin:"tǒng", en:"govern; command; control; unite", level:"advanced" },
  { char:"區", code:"7171", pinyin:"qū", en:"area; district; region", level:"advanced" },
  { char:"保", code:"2629", pinyin:"bǎo", en:"protect; safeguard; defend", level:"advanced" },
  { char:"至", code:"1010", pinyin:"zhì", en:"reach; arrive; extremely; very", level:"advanced" },
  { char:"隊", code:"7823", pinyin:"duì", en:"team; group; army unit", level:"advanced" },
  { char:"形", code:"1242", pinyin:"xíng", en:"form; shape; appearance", level:"advanced" },
  { char:"社", code:"3421", pinyin:"shè", en:"god of the soil and altars to him; group of families; company; society", level:"advanced" },
  { char:"便", code:"2124", pinyin:"biàn", en:"convenience; ease; expedient", level:"advanced" },
  { char:"空", code:"3010", pinyin:"kōng", en:"empty; hollow; bare", level:"advanced" },
  { char:"決", code:"3513", pinyin:"jué", en:"decide; determine; judge", level:"advanced" },
  { char:"治", code:"3316", pinyin:"zhì", en:"govern; regulate; administer", level:"advanced" },
  { char:"展", code:"7723", pinyin:"zhǎn", en:"open; unfold; stretch; extend", level:"advanced" },
  { char:"馬", code:"7132", pinyin:"mǎ", en:"horse; surname; KangXi radical 187", level:"advanced" },
  { char:"科", code:"2490", pinyin:"kē", en:"section; department; science", level:"advanced" },
  { char:"司", code:"1762", pinyin:"sī", en:"take charge of; control; manage; officer", level:"advanced" },
  { char:"五", code:"1010", pinyin:"wǔ", en:"five; surname", level:"advanced" },
  { char:"基", code:"4410", pinyin:"jī", en:"foundation; base", level:"advanced" },
  { char:"眼", code:"6703", pinyin:"yǎn", en:"eye; eyelet; hole; opening", level:"advanced" },
  { char:"書", code:"5060", pinyin:"shū", en:"book; letter; document; writings", level:"advanced" },
  { char:"非", code:"1111", pinyin:"fēi", en:"not; negative; non-; oppose", level:"advanced" },
  { char:"則", code:"6280", pinyin:"zé", en:"rule; law; regulation; grades", level:"advanced" },
  { char:"聽", code:"1413", pinyin:"tīng", en:"hear; listen; understand; obey", level:"advanced" },
  { char:"白", code:"2600", pinyin:"bái", en:"white; pure; unblemished; bright", level:"advanced" },
  { char:"卻", code:"4772", pinyin:"què", en:"still; but; decline; retreat", level:"advanced" },
  { char:"界", code:"4612", pinyin:"jiè", en:"boundary; limit; domain; society; the world", level:"advanced" },
  { char:"達", code:"3430", pinyin:"dá", en:"arrive at; reach; intelligent", level:"advanced" },
  { char:"放", code:"0824", pinyin:"fàng", en:"put; release; free", level:"advanced" },
  { char:"強", code:"1323", pinyin:"qiáng", en:"strong; powerful; energetic", level:"advanced" },
  { char:"即", code:"7772", pinyin:"jí", en:"promptly; quickly; immediately", level:"advanced" },
  { char:"像", code:"2723", pinyin:"xiàng", en:"a picture; image; figure; to resemble", level:"advanced" },
  { char:"難", code:"4051", pinyin:"nán", en:"difficult; arduous; hard; unable", level:"advanced" },
  { char:"且", code:"7710", pinyin:"qiě", en:"moreover; also (post-subject); about to; will soon (pre-verb)", level:"advanced" },
  { char:"權", code:"4491", pinyin:"quán", en:"power; right; authority", level:"advanced" },
  { char:"思", code:"6033", pinyin:"sī", en:"think; consider; ponder; final particle", level:"advanced" },
  { char:"象", code:"2723", pinyin:"xiàng", en:"elephant; ivory; figure; image", level:"advanced" },
  { char:"完", code:"3021", pinyin:"wán", en:"complete; finish; settle; whole", level:"advanced" },
  { char:"設", code:"0764", pinyin:"shè", en:"build; establish; display; particle of hypothesis; supposing", level:"advanced" },
  { char:"式", code:"4310", pinyin:"shì", en:"style; system; formula", level:"advanced" },
  { char:"色", code:"2771", pinyin:"sè", en:"color; tint; hue", level:"advanced" },
  { char:"路", code:"6716", pinyin:"lù", en:"road; path; street; journey", level:"advanced" },
  { char:"記", code:"0761", pinyin:"jì", en:"record; keep in mind; remember", level:"advanced" },
  { char:"南", code:"4022", pinyin:"nán", en:"south; southern part; southward", level:"advanced" },
  { char:"品", code:"6066", pinyin:"pǐn", en:"article; product; commodity", level:"advanced" },
  { char:"住", code:"2021", pinyin:"zhù", en:"reside; live at; dwell", level:"advanced" },
  { char:"告", code:"2460", pinyin:"gào", en:"tell; announce; inform; accuse", level:"advanced" },
  { char:"類", code:"9148", pinyin:"lèi", en:"class; group; kind", level:"advanced" },
  { char:"求", code:"4313", pinyin:"qiú", en:"seek; demand; request; beseech", level:"advanced" },
  { char:"據", code:"5103", pinyin:"jù", en:"to occupy; take possession of; a base", level:"advanced" },
  { char:"程", code:"2691", pinyin:"chéng", en:"journey; trip; schedule; agenda", level:"advanced" },
  { char:"北", code:"1111", pinyin:"běi", en:"north; northern; northward", level:"advanced" },
  { char:"邊", code:"3630", pinyin:"biān", en:"edge; margin; side", level:"advanced" },
  { char:"死", code:"1021", pinyin:"sǐ", en:"die; dead; death", level:"advanced" },
  { char:"張", code:"1123", pinyin:"zhāng", en:"stretch; extend; expand; sheet", level:"advanced" },
  { char:"該", code:"0068", pinyin:"gāi", en:"should; ought to; need to", level:"advanced" },
  { char:"交", code:"0040", pinyin:"jiāo", en:"mix; intersect; exchange; communicate; deliver", level:"advanced" },
  { char:"規", code:"5601", pinyin:"guī", en:"rules; regulations; customs", level:"advanced" },
  { char:"萬", code:"4442", pinyin:"wàn", en:"ten thousand; innumerable", level:"advanced" },
  { char:"取", code:"1714", pinyin:"qǔ", en:"take; receive; obtain; select", level:"advanced" },
  { char:"拉", code:"5001", pinyin:"lā", en:"pull; drag; seize; hold; lengthen", level:"advanced" },
  { char:"格", code:"4796", pinyin:"gé", en:"pattern; standard; form; style", level:"advanced" },
  { char:"望", code:"0710", pinyin:"wàng", en:"to look at; look forward; to hope; expect", level:"advanced" },
  { char:"覺", code:"7721", pinyin:"jué", en:"to wake up from sleep; conscious", level:"advanced" },
  { char:"術", code:"2190", pinyin:"shù", en:"art; skill; special feat; method", level:"advanced" },
  { char:"領", code:"8138", pinyin:"lǐng", en:"neck; collar; lead; guide", level:"advanced" },
  { char:"共", code:"4480", pinyin:"gòng", en:"together with; all; total; to share", level:"advanced" },
  { char:"確", code:"1461", pinyin:"què", en:"sure; certain; real; true", level:"advanced" },
  { char:"傳", code:"2524", pinyin:"chuán", en:"summon; propagate; transmit", level:"advanced" },
  { char:"師", code:"2172", pinyin:"shī", en:"teacher; master; specialist; multitude", level:"advanced" },
  { char:"觀", code:"4621", pinyin:"guān", en:"observe; view; appearance", level:"advanced" },
  { char:"清", code:"3512", pinyin:"qīng", en:"clear; pure; clean; peaceful", level:"advanced" },
  { char:"切", code:"4772", pinyin:"qiè", en:"cut; mince; slice", level:"advanced" },
  { char:"院", code:"7321", pinyin:"yuàn", en:"courtyard; yard; court; school", level:"advanced" },
  { char:"讓", code:"0063", pinyin:"ràng", en:"allow; permit; yield", level:"advanced" },
  { char:"識", code:"0365", pinyin:"shí / shì", en:"recognize; understand; know", level:"advanced" },
  { char:"候", code:"2723", pinyin:"hòu", en:"wait; expect; visit; greet", level:"advanced" },
  { char:"帶", code:"4422", pinyin:"dài", en:"belt; girdle; band", level:"advanced" },
  { char:"導", code:"3834", pinyin:"dǎo", en:"direct; guide; lead", level:"advanced" },
  { char:"爭", code:"2050", pinyin:"zhēng", en:"to dispute; fight; contend", level:"advanced" },
  { char:"運", code:"3730", pinyin:"yùn", en:"luck; fortune; ship; transport", level:"advanced" },
  { char:"笑", code:"8843", pinyin:"xiào", en:"smile; laugh; giggle; snicker", level:"advanced" },
  { char:"飛", code:"1241", pinyin:"fēi", en:"fly; go quickly; dart; high", level:"advanced" },
  { char:"風", code:"7721", pinyin:"fēng", en:"wind; air; manners; atmosphere", level:"advanced" },
  { char:"步", code:"2120", pinyin:"bù", en:"step; pace; walk; stroll", level:"advanced" },
  { char:"改", code:"1874", pinyin:"gǎi", en:"change; alter; improve; remodel", level:"advanced" },
  { char:"收", code:"2874", pinyin:"shōu", en:"gather together; collect; harvest", level:"advanced" },
  { char:"根", code:"4793", pinyin:"gēn", en:"root; base(d on); foundation", level:"advanced" },
  { char:"幹", code:"4844", pinyin:"gàn", en:"trunk of tree or of human body", level:"advanced" },
  { char:"造", code:"3430", pinyin:"zào", en:"construct; build; make", level:"advanced" },
  { char:"言", code:"0060", pinyin:"yán", en:"words; speech; speak; say", level:"advanced" },
  { char:"聯", code:"1217", pinyin:"lián", en:"connect; join; associate; ally", level:"advanced" },
  { char:"持", code:"5404", pinyin:"chí", en:"sustain; support; hold; grasp", level:"advanced" },
  { char:"組", code:"2791", pinyin:"zǔ", en:"class; section; department", level:"advanced" },
  { char:"每", code:"8050", pinyin:"měi", en:"every; each", level:"advanced" },
  { char:"濟", code:"3012", pinyin:"jì", en:"to help; aid; relieve; to ferry", level:"advanced" },
  { char:"親", code:"0691", pinyin:"qīn", en:"relatives; parents; intimate", level:"advanced" },
  { char:"極", code:"4191", pinyin:"jí", en:"extreme; utmost; furthest", level:"advanced" },
  { char:"林", code:"4499", pinyin:"lín", en:"forest", level:"advanced" },
  { char:"服", code:"7724", pinyin:"fú", en:"clothes; wear; dress", level:"advanced" },
  { char:"快", code:"9503", pinyin:"kuài", en:"rapid; quick; speedy", level:"advanced" },
  { char:"辦", code:"0044", pinyin:"bàn", en:"manage; do; handle; deal with", level:"advanced" },
  { char:"議", code:"0865", pinyin:"yì", en:"consult; talk over; discuss", level:"advanced" },
  { char:"往", code:"2021", pinyin:"wǎng", en:"go; depart; past; formerly", level:"advanced" },
  { char:"元", code:"1021", pinyin:"yuán", en:"first; dollar; origin; head", level:"advanced" },
  { char:"英", code:"4453", pinyin:"yīng", en:"petal; flower; leaf; brave", level:"advanced" },
  { char:"士", code:"4010", pinyin:"shì", en:"scholar; gentleman; soldier", level:"advanced" },
  { char:"證", code:"0261", pinyin:"zhèng", en:"proof; evidence; testify; verify", level:"advanced" },
  { char:"近", code:"3230", pinyin:"jìn", en:"near; close; approach; intimate", level:"advanced" },
  { char:"失", code:"2503", pinyin:"shī", en:"lose; make mistake; neglect", level:"advanced" },
  { char:"轉", code:"5504", pinyin:"zhuǎn", en:"shift; move; turn", level:"advanced" },
  { char:"令", code:"8030", pinyin:"lìng", en:"command; order; 'commandant'; magistrate; allow", level:"advanced" },
  { char:"準", code:"3040", pinyin:"zhǔn", en:"rule; guideline; standard", level:"advanced" },
  { char:"布", code:"4022", pinyin:"bù", en:"cotton cloth; textiles; linen", level:"advanced" },
  { char:"始", code:"4346", pinyin:"shǐ", en:"begin; start; then; only then", level:"advanced" },
  { char:"怎", code:"8033", pinyin:"zěn", en:"what? why? how?", level:"advanced" },
  { char:"呢", code:"6701", pinyin:"ne", en:"interrogative or emphatic final; (Cant.) this", level:"advanced" },
  { char:"存", code:"4024", pinyin:"cún", en:"exist; live; be; survive; remain", level:"advanced" },
  { char:"未", code:"5090", pinyin:"wèi", en:"not yet; 8th terrestrial branch", level:"advanced" },
  { char:"遠", code:"3430", pinyin:"yuǎn", en:"distant; remote; far; profound", level:"advanced" },
  { char:"叫", code:"6400", pinyin:"jiào", en:"cry; shout; hail; greet", level:"advanced" },
  { char:"臺", code:"4010", pinyin:"tái", en:"tower; lookout; stage; platform", level:"advanced" },
  { char:"單", code:"6650", pinyin:"dān", en:"single; individual; only; lone", level:"advanced" },
  { char:"影", code:"6292", pinyin:"yǐng", en:"shadow; image; reflection; photograph", level:"advanced" },
  { char:"具", code:"6080", pinyin:"jù", en:"tool; implement; draw up; write", level:"advanced" },
  { char:"羅", code:"6091", pinyin:"luó", en:"net for catching birds; gauze", level:"advanced" },
  { char:"擊", code:"5750", pinyin:"jī", en:"strike; hit; beat; attack", level:"advanced" },
  { char:"流", code:"3411", pinyin:"liú", en:"flow; circulate; drift; class", level:"advanced" },
  { char:"備", code:"2422", pinyin:"bèi", en:"prepare; ready; perfect", level:"advanced" },
  { char:"兵", code:"7280", pinyin:"bīng", en:"soldier; troops", level:"advanced" },
  { char:"連", code:"3530", pinyin:"lián", en:"join; connect; continuous; even", level:"advanced" },
  { char:"調", code:"0762", pinyin:"diào", en:"transfer; move; change; tune", level:"advanced" },
  { char:"深", code:"3719", pinyin:"shēn", en:"deep; depth; far; very; extreme", level:"advanced" },
  { char:"商", code:"0022", pinyin:"shāng", en:"commerce; business; trade", level:"advanced" },
  { char:"算", code:"8844", pinyin:"suàn", en:"count; calculate; figure; plan", level:"advanced" },
  { char:"質", code:"7280", pinyin:"zhì", en:"matter; material; substance", level:"advanced" },
  { char:"團", code:"6034", pinyin:"tuán", en:"sphere; ball; circle; mass", level:"advanced" },
  { char:"集", code:"2090", pinyin:"jí", en:"assemble; collect together", level:"advanced" },
  { char:"百", code:"1060", pinyin:"bǎi", en:"one hundred; numerous; many", level:"advanced" },
  { char:"需", code:"1022", pinyin:"xū", en:"need; require; must", level:"advanced" },
  { char:"價", code:"2128", pinyin:"jià", en:"price; value", level:"advanced" },
  { char:"花", code:"4421", pinyin:"huā", en:"flower; blossoms", level:"advanced" },
  { char:"黨", code:"9033", pinyin:"dǎng", en:"political party; gang; faction", level:"advanced" },
  { char:"城", code:"4315", pinyin:"chéng", en:"castle; city; town; municipality", level:"advanced" },
  { char:"級", code:"2794", pinyin:"jí", en:"level; rank; class; grade", level:"advanced" },
  { char:"整", code:"5810", pinyin:"zhěng", en:"orderly; neat; tidy; whole", level:"advanced" },
  { char:"府", code:"0024", pinyin:"fǔ", en:"prefecture; prefect; government", level:"advanced" },
  { char:"離", code:"0041", pinyin:"lí", en:"leave; depart; go away; separate", level:"advanced" },
  { char:"況", code:"3611", pinyin:"kuàng", en:"condition; situation; furthermore", level:"advanced" },
  { char:"亞", code:"1010", pinyin:"yà", en:"Asia; second; used as a prefix to names", level:"advanced" },
  { char:"請", code:"0562", pinyin:"qǐng", en:"ask; request; invite; please", level:"advanced" },
  { char:"技", code:"5404", pinyin:"jì", en:"skill; ability; talent", level:"advanced" },
  { char:"際", code:"7729", pinyin:"jì", en:"border; boundary; juncture", level:"advanced" },
  { char:"約", code:"2792", pinyin:"yuē", en:"treaty; agreement; covenant", level:"advanced" },
  { char:"示", code:"1090", pinyin:"shì", en:"show; manifest; demonstrate", level:"advanced" },
  { char:"復", code:"2824", pinyin:"fù", en:"return; repeat; repeatedly", level:"advanced" },
  { char:"病", code:"0012", pinyin:"bìng", en:"illness; sickness; disease", level:"advanced" },
  { char:"息", code:"2633", pinyin:"xī", en:"rest; put stop to; end", level:"advanced" },
  { char:"究", code:"3041", pinyin:"jiū", en:"examine; investigate", level:"advanced" },
  { char:"線", code:"2693", pinyin:"xiàn", en:"thread; line; wire; clue", level:"advanced" },
  { char:"似", code:"2820", pinyin:"shì", en:"resemble; similar to; as if; seem", level:"advanced" },
  { char:"官", code:"3077", pinyin:"guān", en:"official; public servant", level:"advanced" },
  { char:"斷", code:"2272", pinyin:"duàn", en:"sever; cut off; interrupt", level:"advanced" },
  { char:"精", code:"9592", pinyin:"jīng", en:"essence; semen; spirit", level:"advanced" },
  { char:"滿", code:"3412", pinyin:"mǎn", en:"fill; full; satisfied", level:"advanced" },
  { char:"支", code:"4040", pinyin:"zhī", en:"disperse; pay; support; branch", level:"advanced" },
  { char:"視", code:"3621", pinyin:"shì", en:"look at; inspect; observe", level:"advanced" },
  { char:"消", code:"3912", pinyin:"xiāo", en:"vanish; die out; melt away", level:"advanced" },
  { char:"越", code:"4380", pinyin:"yuè", en:"exceed; go beyond; the more ...", level:"advanced" },
  { char:"器", code:"6666", pinyin:"qì", en:"receptacle; vessel; instrument", level:"advanced" },
  { char:"容", code:"3060", pinyin:"róng", en:"looks; appearance; figure; form", level:"advanced" },
  { char:"照", code:"6733", pinyin:"zhào", en:"shine; illumine; reflect", level:"advanced" },
  { char:"須", code:"2128", pinyin:"xū", en:"must; have to; necessary; moment; whiskers", level:"advanced" },
  { char:"九", code:"4001", pinyin:"jiǔ", en:"nine", level:"advanced" },
  { char:"增", code:"4816", pinyin:"zēng", en:"increase; add to; augment", level:"advanced" },
  { char:"研", code:"1164", pinyin:"yán", en:"grind; rub; study; research", level:"advanced" },
  { char:"寫", code:"3032", pinyin:"xiě", en:"write; draw; sketch; compose", level:"advanced" },
  { char:"稱", code:"2295", pinyin:"chēng", en:"call; name; brand; address; say", level:"advanced" },
  { char:"企", code:"8010", pinyin:"qǐ", en:"plan a project; stand on tiptoe", level:"advanced" },
  { char:"功", code:"1412", pinyin:"gōng", en:"achievement; merit; good result", level:"advanced" },
  { char:"嗎", code:"6102", pinyin:"ma", en:"final interrogative particle", level:"advanced" },
  { char:"包", code:"2771", pinyin:"bāo", en:"wrap; pack; bundle; package", level:"advanced" },
  { char:"片", code:"2202", pinyin:"piàn", en:"slice; splinter; strip; rad. 91", level:"advanced" },
  { char:"史", code:"5000", pinyin:"shǐ", en:"history; chronicle; annals", level:"advanced" },
  { char:"委", code:"2040", pinyin:"wěi", en:"appoint; send; commission", level:"advanced" },
  { char:"乎", code:"2040", pinyin:"hū", en:"interrogative or exclamatory final particle", level:"advanced" },
  { char:"查", code:"4010", pinyin:"chá", en:"investigate; examine; seek into", level:"advanced" },
  { char:"輕", code:"5101", pinyin:"qīng", en:"light; easy; simple; gentle", level:"advanced" },
  { char:"易", code:"6022", pinyin:"yì", en:"change; easy", level:"advanced" },
  { char:"早", code:"6040", pinyin:"zǎo", en:"early; soon; morning", level:"advanced" },
  { char:"曾", code:"8060", pinyin:"céng", en:"already; sign of past", level:"advanced" },
  { char:"除", code:"7829", pinyin:"chú", en:"eliminate; remove; except", level:"advanced" },
  { char:"農", code:"5523", pinyin:"nóng", en:"agriculture; farming; farmer", level:"advanced" },
  { char:"找", code:"5305", pinyin:"zhǎo", en:"search; seek; look for; find", level:"advanced" },
  { char:"裝", code:"2473", pinyin:"zhuāng", en:"dress; clothes; decorate; fill", level:"advanced" },
  { char:"廣", code:"0028", pinyin:"guǎng", en:"broad; wide; extensive", level:"advanced" },
  { char:"顯", code:"6138", pinyin:"xiǎn", en:"manifest; display; evident; clear", level:"advanced" },
  { char:"吧", code:"6071", pinyin:"ba", en:"emphatic final particle", level:"advanced" },
  { char:"阿", code:"7122", pinyin:"ā", en:"prefix for people's names; used in transliteration", level:"advanced" },
  { char:"李", code:"4040", pinyin:"lǐ", en:"plum; judge; surname", level:"advanced" },
  { char:"標", code:"4199", pinyin:"biāo", en:"a mark; symbol; label", level:"advanced" },
  { char:"談", code:"0968", pinyin:"tán", en:"talk; conversation; surname", level:"advanced" },
  { char:"吃", code:"6801", pinyin:"chī", en:"eat; drink; suffer; endure; bear", level:"advanced" },
  { char:"圖", code:"6060", pinyin:"tú", en:"diagram; chart; map; picture", level:"advanced" },
  { char:"念", code:"8033", pinyin:"niàn", en:"think of; recall; study", level:"advanced" },
  { char:"六", code:"0080", pinyin:"liù", en:"number six", level:"advanced" },
  { char:"引", code:"1220", pinyin:"yǐn", en:"to pull; draw out; attract; to stretch", level:"advanced" },
  { char:"歷", code:"7121", pinyin:"lì", en:"take place; past; history", level:"advanced" },
  { char:"首", code:"8060", pinyin:"shǒu", en:"head; first; leader; chief; a poem", level:"advanced" },
  { char:"醫", code:"7760", pinyin:"yī", en:"cure; heal; doctor; medical", level:"advanced" },
  { char:"局", code:"7722", pinyin:"jú", en:"bureau; office; circumstance", level:"advanced" },
  { char:"突", code:"3043", pinyin:"tū", en:"suddenly; abruptly; unexpectedly", level:"advanced" },
  { char:"專", code:"5034", pinyin:"zhuān", en:"monopolize; take sole possession", level:"advanced" },
  { char:"費", code:"5580", pinyin:"fèi", en:"expenses; expenditures; fee", level:"advanced" },
  { char:"號", code:"6121", pinyin:"hào", en:"mark; sign; symbol; number", level:"advanced" },
  { char:"盡", code:"5010", pinyin:"jǐn", en:"exhaust; use up; deplete", level:"advanced" },
  { char:"另", code:"6042", pinyin:"lìng", en:"another; separate; other", level:"advanced" },
  { char:"周", code:"7722", pinyin:"zhōu", en:"Zhou dynasty; circumference", level:"advanced" },
  { char:"較", code:"5004", pinyin:"jiào", en:"compare; comparatively; more", level:"advanced" },
  { char:"注", code:"3011", pinyin:"zhù", en:"concentrate; focus; direct", level:"advanced" },
  { char:"僅", code:"2421", pinyin:"jǐn", en:"only; merely; solely", level:"advanced" },
  { char:"考", code:"4420", pinyin:"kǎo", en:"examine; test; investigate", level:"advanced" },
  { char:"落", code:"4416", pinyin:"luò", en:"fall; drop; net income; surplus", level:"advanced" },
  { char:"青", code:"5022", pinyin:"qīng", en:"blue; green; black; young", level:"advanced" },
  { char:"隨", code:"7423", pinyin:"suí", en:"follow; listen to; submit; to accompany; subsequently", level:"advanced" },
  { char:"選", code:"3730", pinyin:"xuǎn", en:"choose; select; elect; election", level:"advanced" },
  { char:"列", code:"1220", pinyin:"liè", en:"a line; to arrange in order; classify", level:"advanced" },
  { char:"武", code:"1314", pinyin:"wǔ", en:"military; martial; warlike", level:"advanced" },
  { char:"紅", code:"2191", pinyin:"hóng", en:"red; vermillion; blush; flush", level:"advanced" },
  { char:"響", code:"2760", pinyin:"xiǎng", en:"make sound; make noise; sound", level:"advanced" },
  { char:"雖", code:"6011", pinyin:"suī", en:"although; even if", level:"advanced" },
  { char:"推", code:"5001", pinyin:"tuī", en:"push; expel; push forward", level:"advanced" },
  { char:"勢", code:"4542", pinyin:"shì", en:"power; force; tendency", level:"advanced" },
  { char:"參", code:"2320", pinyin:"cān", en:"take part in; intervene; ginseng", level:"advanced" },
  { char:"希", code:"4022", pinyin:"xī", en:"rare; hope; expect; strive for", level:"advanced" },
  { char:"古", code:"4060", pinyin:"gǔ", en:"old; classic; ancient", level:"advanced" },
  { char:"構", code:"4594", pinyin:"gòu", en:"frame; building; structure", level:"advanced" },
  { char:"房", code:"3022", pinyin:"fáng", en:"house; building; room", level:"advanced" },
  { char:"節", code:"8872", pinyin:"jié", en:"knot; node; joint; section", level:"advanced" },
  { char:"投", code:"5704", pinyin:"tóu", en:"throw; cast; fling", level:"advanced" },
  { char:"某", code:"4490", pinyin:"mǒu", en:"certain thing or person", level:"advanced" },
  { char:"案", code:"3090", pinyin:"àn", en:"table; bench; legal case", level:"advanced" },
  { char:"黑", code:"6033", pinyin:"hēi", en:"black; dark; evil; sinister", level:"advanced" },
  { char:"維", code:"2091", pinyin:"wéi", en:"maintain; preserve; safeguard", level:"advanced" },
  { char:"革", code:"4450", pinyin:"gé", en:"leather; animal hides; rad. 177", level:"advanced" },
  { char:"劃", code:"5210", pinyin:"huà", en:"divide; mark off; lay boundary", level:"advanced" },
  { char:"敵", code:"0824", pinyin:"dí", en:"enemy; foe; rival; resist", level:"advanced" },
  { char:"致", code:"1814", pinyin:"zhì", en:"send; deliver; present; cause", level:"advanced" },
  { char:"陳", code:"7529", pinyin:"chén", en:"exhibit", level:"advanced" },
  { char:"律", code:"2520", pinyin:"lǜ", en:"statute; principle; regulation", level:"advanced" },
  { char:"足", code:"6080", pinyin:"zú", en:"foot; attain; satisfy; enough", level:"advanced" },
  { char:"態", code:"2133", pinyin:"tài", en:"manner; bearing; attitude", level:"advanced" },
  { char:"護", code:"0464", pinyin:"hù", en:"protect; guard; defend", level:"advanced" },
  { char:"七", code:"4071", pinyin:"qī", en:"seven", level:"advanced" },
  { char:"興", code:"7780", pinyin:"xìng", en:"thrive; prosper; flourish", level:"advanced" },
  { char:"派", code:"3213", pinyin:"pài", en:"school of thought; sect; branch", level:"advanced" },
  { char:"孩", code:"1048", pinyin:"hái", en:"baby; child; children", level:"advanced" },
  { char:"驗", code:"7833", pinyin:"yàn", en:"test; examine; inspect; verify", level:"advanced" },
  { char:"責", code:"5080", pinyin:"zé", en:"one's responsibility; duty", level:"advanced" },
  { char:"營", code:"9960", pinyin:"yíng", en:"encampment; barracks; manage", level:"advanced" },
  { char:"星", code:"6010", pinyin:"xīng", en:"a star; planet; any point of light", level:"advanced" },
  { char:"夠", code:"2722", pinyin:"gòu", en:"enough; adequate", level:"advanced" },
  { char:"章", code:"0040", pinyin:"zhāng", en:"composition; chapter; section", level:"advanced" },
  { char:"音", code:"0060", pinyin:"yīn", en:"sound; tone; pitch", level:"advanced" },
  { char:"跟", code:"6713", pinyin:"gēn", en:"heel; to follow; accompany; with", level:"advanced" },
  { char:"志", code:"4033", pinyin:"zhì", en:"purpose; will; determination; annals", level:"advanced" },
  { char:"底", code:"0024", pinyin:"dǐ", en:"bottom; underneath; underside", level:"advanced" },
  { char:"站", code:"0116", pinyin:"zhàn", en:"stand up; a stand; station", level:"advanced" },
  { char:"嚴", code:"6624", pinyin:"yán", en:"strict; rigorous; rigid; stern", level:"advanced" },
  { char:"巴", code:"7771", pinyin:"bā", en:"greatly desire; anxiously hope", level:"advanced" },
  { char:"例", code:"2220", pinyin:"lì", en:"precedent; example; regulation", level:"advanced" },
  { char:"防", code:"7022", pinyin:"fáng", en:"defend; prevent; embankment", level:"advanced" },
  { char:"族", code:"0823", pinyin:"zú", en:"a family clan; ethnic group; tribe", level:"advanced" },
  { char:"供", code:"2428", pinyin:"gōng", en:"supply; provide for; offer in worship", level:"advanced" },
  { char:"效", code:"0844", pinyin:"xiào", en:"result; effect; effectiveness", level:"advanced" },
  { char:"續", code:"2498", pinyin:"xù", en:"continue; carry on; succeed", level:"advanced" },
  { char:"施", code:"0821", pinyin:"shī", en:"grant; bestow; give; act; name", level:"advanced" },
  { char:"留", code:"7760", pinyin:"liú", en:"stop; halt; stay; detain", level:"advanced" },
  { char:"講", code:"0565", pinyin:"jiǎng", en:"explain; discuss; talk", level:"advanced" },
  { char:"型", code:"1210", pinyin:"xíng", en:"pattern; model; type; law; mold", level:"advanced" },
  { char:"料", code:"9490", pinyin:"liào", en:"consider; conjecture; materials; ingredients", level:"advanced" },
  { char:"終", code:"2793", pinyin:"zhōng", en:"end; finally; in the end", level:"advanced" },
  { char:"答", code:"8860", pinyin:"dá", en:"answer; reply; return; assent to", level:"advanced" },
  { char:"緊", code:"7790", pinyin:"jǐn", en:"tense; tight; taut; firm", level:"advanced" },
  { char:"黃", code:"4480", pinyin:"huáng", en:"yellow; surname", level:"advanced" },
  { char:"絕", code:"2791", pinyin:"jué", en:"cut; sever; break off", level:"advanced" },
  { char:"奇", code:"4062", pinyin:"qí", en:"strange; unusual; uncanny", level:"advanced" },
  { char:"察", code:"3090", pinyin:"chá", en:"examine; investigate; notice", level:"advanced" },
  { char:"母", code:"7750", pinyin:"mǔ", en:"mother; female elders; female", level:"advanced" },
  { char:"京", code:"0090", pinyin:"jīng", en:"capital city", level:"advanced" },
  { char:"段", code:"7744", pinyin:"duàn", en:"section; piece; division", level:"advanced" },
  { char:"依", code:"2023", pinyin:"yī", en:"rely on; be set in; consent; obey a wish", level:"advanced" },
  { char:"批", code:"5101", pinyin:"pī", en:"comment; criticize; wholesale", level:"advanced" },
  { char:"項", code:"1118", pinyin:"xiàng", en:"neck; nape of neck; sum; funds", level:"advanced" },
  { char:"故", code:"4864", pinyin:"gù", en:"ancient; old; reason; because", level:"advanced" },
  { char:"按", code:"5304", pinyin:"àn", en:"put hand on; press down with hand", level:"advanced" },
  { char:"河", code:"3112", pinyin:"hé", en:"river; stream; yellow river", level:"advanced" },
  { char:"圍", code:"6050", pinyin:"wéi", en:"surround; encircle; corral", level:"advanced" },
  { char:"江", code:"3111", pinyin:"jiāng", en:"large river; yangzi; surname", level:"advanced" },
  { char:"織", code:"2395", pinyin:"zhī", en:"weave; knit; organize; unite", level:"advanced" },
  { char:"害", code:"3060", pinyin:"hài", en:"injure; harm; destroy; kill", level:"advanced" },
  { char:"鬥", code:"7711", pinyin:"dòu", en:"struggle; fight; compete", level:"advanced" },
  { char:"雙", code:"2040", pinyin:"shuāng", en:"set of two; pair; couple; both", level:"advanced" },
  { char:"境", code:"4011", pinyin:"jìng", en:"boundary; frontier; area; region", level:"advanced" },
  { char:"客", code:"3060", pinyin:"kè", en:"guest; traveller; customer", level:"advanced" },
  { char:"紀", code:"2791", pinyin:"jì", en:"record; annal; historical account", level:"advanced" },
  { char:"採", code:"5209", pinyin:"cǎi", en:"gather; collect; pick; select", level:"advanced" },
  { char:"舉", code:"7750", pinyin:"jǔ", en:"raise; lift up; recommend", level:"advanced" },
  { char:"殺", code:"4794", pinyin:"shā", en:"kill; slaughter; murder; hurt; to pare off", level:"advanced" },
  { char:"攻", code:"1814", pinyin:"gōng", en:"attack; assault; criticize", level:"advanced" },
  { char:"父", code:"8040", pinyin:"fù", en:"father; KangXi radical 88", level:"advanced" },
  { char:"蘇", code:"4439", pinyin:"sū", en:"revive; resurrect; a species of thyme; transliteration of 'Soviet'", level:"advanced" },
  { char:"密", code:"3077", pinyin:"mì", en:"dense; thick; close; intimate", level:"advanced" },
  { char:"低", code:"2224", pinyin:"dī", en:"low; to lower; hang; bend", level:"advanced" },
  { char:"朝", code:"4742", pinyin:"cháo", en:"dynasty; morning", level:"advanced" },
  { char:"訴", code:"0263", pinyin:"sù", en:"accuse; sue; inform; narrate", level:"advanced" },
  { char:"止", code:"2110", pinyin:"zhǐ", en:"stop; halt; desist; detain", level:"advanced" },
  { char:"細", code:"2690", pinyin:"xì", en:"fine; tiny; slender; thin", level:"advanced" },
  { char:"願", code:"7128", pinyin:"yuàn", en:"desire; want; wish; ambition", level:"advanced" },
  { char:"千", code:"2040", pinyin:"qiān", en:"thousand; many; numerous; very; (Cant.) a cheater; swindler", level:"advanced" },
  { char:"值", code:"2421", pinyin:"zhí", en:"price", level:"advanced" },
  { char:"仍", code:"2722", pinyin:"réng", en:"yet; still; as ever; again; keep -ing", level:"advanced" },
  { char:"男", code:"6042", pinyin:"nán", en:"male", level:"advanced" },
  { char:"錢", code:"8315", pinyin:"qián", en:"money; currency; coins", level:"advanced" },
  { char:"破", code:"1464", pinyin:"pò", en:"break; ruin; destroy; rout", level:"advanced" },
  { char:"網", code:"2792", pinyin:"wǎng", en:"net; web; network", level:"advanced" },
  { char:"熱", code:"4533", pinyin:"rè", en:"hot; heat; fever; restless; zeal", level:"advanced" },
  { char:"助", code:"7412", pinyin:"zhù", en:"help; aid; assist", level:"advanced" },
  { char:"倒", code:"2220", pinyin:"dào", en:"fall over; lie down; take turns", level:"advanced" },
  { char:"育", code:"0022", pinyin:"yù", en:"produce; give birth to; educate", level:"advanced" },
  { char:"屬", code:"7722", pinyin:"shǔ", en:"class; category; type; to belong to", level:"advanced" },
  { char:"坐", code:"8810", pinyin:"zuò", en:"sit; seat; ride; travel by", level:"advanced" },
  { char:"帝", code:"0022", pinyin:"dì", en:"supreme ruler; emperor; god", level:"advanced" },
  { char:"限", code:"7723", pinyin:"xiàn", en:"boundary; limit; line", level:"advanced" },
  { char:"船", code:"2846", pinyin:"chuán", en:"ship; boat; vessel", level:"advanced" },
  { char:"臉", code:"7828", pinyin:"liǎn", en:"face; cheek; reputation", level:"advanced" },
  { char:"職", code:"1315", pinyin:"zhí", en:"duty; profession; office; post", level:"advanced" },
  { char:"速", code:"3530", pinyin:"sù", en:"quick; prompt; speedy", level:"advanced" },
  { char:"刻", code:"0280", pinyin:"kè", en:"carve; engrave; quarter hour", level:"advanced" },
  { char:"樂", code:"2290", pinyin:"lè", en:"happy; glad; enjoyable; music", level:"advanced" },
  { char:"否", code:"1060", pinyin:"fǒu", en:"not; no; negative; final particle", level:"advanced" },
  { char:"剛", code:"7220", pinyin:"gāng", en:"hard; tough; rigid", level:"advanced" },
  { char:"威", code:"5320", pinyin:"wēi", en:"pomp; power; powerful; dominate", level:"advanced" },
  { char:"毛", code:"2071", pinyin:"máo", en:"hair; fur; feathers; coarse", level:"advanced" },
  { char:"狀", code:"3313", pinyin:"zhuàng", en:"form; appearance; shape; official", level:"advanced" },
  { char:"率", code:"0040", pinyin:"lǜ", en:"to lead; ratio; rate; limit", level:"advanced" },
  { char:"甚", code:"4471", pinyin:"shén", en:"great extent; considerably", level:"advanced" },
  { char:"獨", code:"4622", pinyin:"dú", en:"alone; single; solitary", level:"advanced" },
  { char:"球", code:"1313", pinyin:"qiú", en:"ball; sphere; globe; round", level:"advanced" },
  { char:"般", code:"2744", pinyin:"bān", en:"sort; manner; kind", level:"advanced" },
  { char:"普", code:"8060", pinyin:"pǔ", en:"universal; general; widespread", level:"advanced" },
  { char:"怕", code:"9600", pinyin:"pà", en:"to fear; be afraid of; apprehensive", level:"advanced" },
  { char:"彈", code:"1625", pinyin:"dàn", en:"pellet; bullet; shot", level:"advanced" },
  { char:"校", code:"4094", pinyin:"xiào", en:"school; military field officer", level:"advanced" },
  { char:"苦", code:"4460", pinyin:"kǔ", en:"bitter; hardship; suffering", level:"advanced" },
  { char:"創", code:"8260", pinyin:"chuàng", en:"establish; create; knife cut", level:"advanced" },
  { char:"假", code:"2724", pinyin:"jiǎ", en:"falsehood; deception; vacation", level:"advanced" },
  { char:"久", code:"2780", pinyin:"jiǔ", en:"long time (ago); time passage; grow late", level:"advanced" },
  { char:"錯", code:"8416", pinyin:"cuò", en:"error; blunder; mistake", level:"advanced" },
  { char:"承", code:"1723", pinyin:"chéng", en:"inherit; receive; succeed", level:"advanced" },
  { char:"印", code:"7772", pinyin:"yìn", en:"print; seal; stamp", level:"advanced" },
  { char:"晚", code:"6701", pinyin:"wǎn", en:"night; evening; late", level:"advanced" },
  { char:"蘭", code:"4422", pinyin:"lán", en:"orchid; elegant; graceful", level:"advanced" },
  { char:"試", code:"0364", pinyin:"shì", en:"test; try; experiment", level:"advanced" },
  { char:"股", code:"7724", pinyin:"gǔ", en:"thighs; haunches; rump; share", level:"advanced" },
  { char:"拿", code:"8050", pinyin:"ná", en:"take; hold; grasp; bring; with", level:"advanced" },
  { char:"腦", code:"7226", pinyin:"nǎo", en:"brain", level:"advanced" },
  { char:"預", code:"1128", pinyin:"yù", en:"prepare; arrange; in advance", level:"advanced" },
  { char:"誰", code:"0061", pinyin:"shuí / shéi", en:"who? whom? whose? anyone?", level:"advanced" },
  { char:"益", code:"8010", pinyin:"yì", en:"profit; benefit; advantage", level:"advanced" },
  { char:"陽", code:"7622", pinyin:"yáng", en:"'male' principle; light; sun", level:"advanced" },
  { char:"若", code:"4460", pinyin:"ruò", en:"if; supposing; assuming; similar", level:"advanced" },
  { char:"哪", code:"6702", pinyin:"nǎ", en:"which? where? how?", level:"advanced" },
  { char:"微", code:"2824", pinyin:"wēi", en:"small; prefix micro-; trifling", level:"advanced" },
  { char:"尼", code:"7721", pinyin:"ní", en:"Buddhist nun; transliteration", level:"advanced" },
  { char:"繼", code:"2291", pinyin:"jì", en:"continue; maintain; carry on", level:"advanced" },
  { char:"送", code:"3830", pinyin:"sòng", en:"see off; send off; dispatch; give", level:"advanced" },
  { char:"急", code:"2733", pinyin:"jí", en:"quick; quickly; urgent; pressing", level:"advanced" },
  { char:"血", code:"2710", pinyin:"xuè", en:"blood; radical number 143", level:"advanced" },
  { char:"驚", code:"4832", pinyin:"jīng", en:"frighten; surprise; startle", level:"advanced" },
  { char:"傷", code:"2822", pinyin:"shāng", en:"wound; injury; fall ill from", level:"advanced" },
  { char:"素", code:"5090", pinyin:"sù", en:"white (silk); plain; vegetarian; formerly; normally", level:"advanced" },
  { char:"藥", code:"4490", pinyin:"yào", en:"drugs; pharmaceuticals; medicine", level:"advanced" },
  { char:"適", code:"3030", pinyin:"shì", en:"match; comfortable; just", level:"advanced" },
  { char:"波", code:"3414", pinyin:"bō", en:"waves; breakers; undulations", level:"advanced" },
  { char:"夜", code:"0024", pinyin:"yè", en:"night; dark; in night; by night", level:"advanced" },
  { char:"省", code:"9060", pinyin:"shěng", en:"province; save; economize", level:"advanced" },
  { char:"初", code:"3722", pinyin:"chū", en:"beginning; initial; primary", level:"advanced" },
  { char:"喜", code:"4060", pinyin:"xǐ", en:"like; love; enjoy; joyful thing", level:"advanced" },
  { char:"衛", code:"2122", pinyin:"wèi", en:"guard; protect; defend", level:"advanced" },
  { char:"源", code:"3119", pinyin:"yuán", en:"spring; source", level:"advanced" },
  { char:"食", code:"8073", pinyin:"shí", en:"eat; meal; food; KangXi radical number 184", level:"advanced" },
  { char:"險", code:"7828", pinyin:"xiǎn", en:"narrow pass; strategic point; dangerous", level:"advanced" },
  { char:"待", code:"2424", pinyin:"dài", en:"treat; entertain; receive; wait", level:"advanced" },
  { char:"述", code:"3330", pinyin:"shù", en:"narrate; state; express", level:"advanced" },
  { char:"陸", code:"7421", pinyin:"lù", en:"land; continental; army; an accounting form of U+516D 六 (six)", level:"advanced" },
  { char:"習", code:"1760", pinyin:"xí", en:"practice; flapping wings", level:"advanced" },
  { char:"置", code:"6071", pinyin:"zhì", en:"place; lay out; set aside", level:"advanced" },
  { char:"居", code:"7726", pinyin:"jū", en:"live; dwell; reside", level:"advanced" },
  { char:"勞", code:"9942", pinyin:"láo", en:"labor; toil; do manual work", level:"advanced" },
  { char:"財", code:"6480", pinyin:"cái", en:"wealth; valuables; riches", level:"advanced" },
  { char:"環", code:"1613", pinyin:"huán", en:"jade ring or bracelet; ring", level:"advanced" },
  { char:"排", code:"5101", pinyin:"pái", en:"row; rank; line", level:"advanced" },
  { char:"納", code:"2492", pinyin:"nà", en:"admit; take; receive", level:"advanced" },
  { char:"歡", code:"4728", pinyin:"huān", en:"happy; pleased; glad; joy; to enjoy", level:"advanced" },
  { char:"雷", code:"1060", pinyin:"léi", en:"thunder", level:"advanced" },
  { char:"警", code:"4860", pinyin:"jǐng", en:"guard; watch; alert; alarm", level:"advanced" },
  { char:"獲", code:"4424", pinyin:"huò", en:"obtain; get; receive; seize", level:"advanced" },
  { char:"模", code:"4493", pinyin:"mó", en:"model; standard; pattern; copy", level:"advanced" },
  { char:"充", code:"0021", pinyin:"chōng", en:"fill; be full; supply", level:"advanced" },
  { char:"負", code:"2780", pinyin:"fù", en:"load; burden; carry; bear", level:"advanced" },
  { char:"雲", code:"1073", pinyin:"yún", en:"clouds; Yunnan province", level:"advanced" },
  { char:"停", code:"2022", pinyin:"tíng", en:"stop; suspend; delay; suitable", level:"advanced" },
  { char:"遊", code:"3830", pinyin:"yóu", en:"wander; roam; travel", level:"advanced" },
  { char:"龍", code:"0121", pinyin:"lóng", en:"dragon; symbolic of emperor", level:"advanced" },
  { char:"樹", code:"4490", pinyin:"shù", en:"tree; plant; set up; establish", level:"advanced" },
  { char:"疑", code:"2748", pinyin:"yí", en:"doubt; question; suspect", level:"advanced" },
  { char:"層", code:"7726", pinyin:"céng", en:"story; layer; floor", level:"advanced" }
];
